// Copyright 2024-2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace AgentScope.Core.Message;

/// <summary>
/// Message role enum, identifying the role of the message sender.
/// 消息角色枚举，用于标识消息发送者的角色。
/// </summary>
public enum MsgRole
{
    /// <summary>
    /// System role — messages from the system (e.g., instructions, context).
    /// 系统角色——来自系统的消息（例如指令、上下文）。
    /// </summary>
    System,

    /// <summary>
    /// User role — messages from the end user.
    /// 用户角色——来自最终用户的消息。
    /// </summary>
    User,

    /// <summary>
    /// Assistant role — messages generated by the AI assistant.
    /// 助手角色——由 AI 助手生成的消息。
    /// </summary>
    Assistant,

    /// <summary>
    /// Tool role — messages returned by tool/function calls.
    /// 工具角色——由工具/函数调用返回的消息。
    /// </summary>
    Tool
}
