<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>AgentScope.Extensions.Skill.PostgreSql</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AgentScope.Extensions\AgentScope.Extensions.csproj" />    <PackageReference Include="Npgsql">
  <Version>10.0.3</Version>
</PackageReference>  </ItemGroup>
</Project>

