// Copyright 2024-2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Collections.Generic;

namespace AgentScope.Core.Formatter.DashScope;

/// <summary>
/// 解析后的响应，表示从 DashScope API 返回的结构化结果。
/// Parsed response from DashScope API.
/// </summary>
public class ParsedResponse
{
    /// <summary>
    /// 响应 ID，唯一标识一次请求。
    /// Response ID, uniquely identifying a request.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// 模型名称，处理请求的模型标识。
    /// Model name, the identifier of the model that processed the request.
    /// </summary>
    public string? Model { get; set; }

    /// <summary>
    /// 文本内容，模型生成的回复文本。
    /// Text content, the response text generated by the model.
    /// </summary>
    public string? TextContent { get; set; }

    /// <summary>
    /// 停止原因，描述生成停止的原因（如 "stop", "length", "tool_calls"）。
    /// Finish reason, describing why generation stopped (e.g., "stop", "length", "tool_calls").
    /// </summary>
    public string? FinishReason { get; set; }

    /// <summary>
    /// 工具调用列表，模型请求调用的函数集合。
    /// Tool calls, the set of functions the model is requesting to invoke.
    /// </summary>
    public List<ToolCall>? ToolCalls { get; set; }

    /// <summary>
    /// Token 使用情况，统计输入输出 token 数量。
    /// Token usage statistics for input and output tokens.
    /// </summary>
    public UsageInfo? Usage { get; set; }

    /// <summary>
    /// 思考内容，用于推理模型（如 qwen-plus）输出的中间推理过程。
    /// Thinking content, intermediate reasoning output for reasoning models (e.g., qwen-plus).
    /// </summary>
    public string? ThinkingContent { get; set; }
}

/// <summary>
/// 工具调用信息，表示模型发起的一次函数调用。
/// Tool call information representing a function call initiated by the model.
/// </summary>
public class ToolCall
{
    /// <summary>
    /// 工具调用 ID，唯一标识一次调用。
    /// Tool call ID, uniquely identifying a call.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// 工具类型，通常为 "function"。
    /// Tool type, typically "function".
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// 函数信息，包含函数名称和参数。
    /// Function info containing the function name and arguments.
    /// </summary>
    public FunctionInfo? Function { get; set; }
}

/// <summary>
/// 函数信息，描述被调用函数的名称和参数。
/// Function information describing the called function's name and arguments.
/// </summary>
public class FunctionInfo
{
    /// <summary>
    /// 函数名称，要调用的函数标识。
    /// Function name, the identifier of the function to call.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// 参数 JSON，函数的 JSON 序列化参数。
    /// Arguments JSON, the JSON-serialized arguments for the function.
    /// </summary>
    public string? Arguments { get; set; }
}

/// <summary>
/// Token 使用信息，统计请求的 token 消耗。
/// Token usage information, tracking token consumption for the request.
/// </summary>
public class UsageInfo
{
    /// <summary>
    /// 输入 token 数，提示部分的 token 数量。
    /// Input tokens, the number of tokens in the prompt.
    /// </summary>
    public int InputTokens { get; set; }

    /// <summary>
    /// 输出 token 数，生成内容的 token 数量。
    /// Output tokens, the number of tokens in the generated content.
    /// </summary>
    public int OutputTokens { get; set; }

    /// <summary>
    /// 总 token 数，输入和输出的 token 总数。
    /// Total tokens, the sum of input and output tokens.
    /// </summary>
    public int TotalTokens { get; set; }
}
