<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>AgentScope.Extensions.Vector.Qdrant</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AgentScope.Extensions\AgentScope.Extensions.csproj" />
    <PackageReference Include="Qdrant.Client" Version="1.15.0" />
  </ItemGroup>
</Project>
