// Copyright 2024-2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace AgentScope.Core.Formatter.DashScope.Dto;

/// <summary>
/// DashScope API response DTO.
/// DashScope API 响应 DTO
/// 
/// Java参考: io.agentscope.core.formatter.dashscope.dto.DashScopeResponse
/// </summary>
public class DashScopeResponse
{
    /// <summary>
    /// Unique request identifier
    /// </summary>
    [JsonPropertyName("request_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? RequestId { get; set; }

    /// <summary>
    /// The output containing choices
    /// </summary>
    [JsonPropertyName("output")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DashScopeOutput? Output { get; set; }

    /// <summary>
    /// Token usage statistics
    /// </summary>
    [JsonPropertyName("usage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DashScopeUsage? Usage { get; set; }

    /// <summary>
    /// Error code (if request failed)
    /// </summary>
    [JsonPropertyName("code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Code { get; set; }

    /// <summary>
    /// Error message (if request failed)
    /// </summary>
    [JsonPropertyName("message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Message { get; set; }

    /// <summary>
    /// Check if this response represents an error
    /// </summary>
    [JsonIgnore]
    public bool IsError => !string.IsNullOrEmpty(Code);
}

/// <summary>
/// DashScope output DTO.
/// DashScope 输出 DTO
/// </summary>
public class DashScopeOutput
{
    /// <summary>
    /// List of choices (typically one for chat completions)
    /// </summary>
    [JsonPropertyName("choices")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<DashScopeChoice>? Choices { get; set; }

    /// <summary>
    /// Top-level finish reason
    /// </summary>
    [JsonPropertyName("finish_reason")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? FinishReason { get; set; }

    /// <summary>
    /// Legacy text field (for result_format="text")
    /// </summary>
    [JsonPropertyName("text")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Text { get; set; }

    /// <summary>
    /// Get the first choice if available
    /// </summary>
    [JsonIgnore]
    public DashScopeChoice? FirstChoice => Choices?.Count > 0 ? Choices[0] : null;
}

/// <summary>
/// DashScope choice DTO.
/// DashScope 选项 DTO
/// </summary>
public class DashScopeChoice
{
    /// <summary>
    /// The message generated by the model
    /// </summary>
    [JsonPropertyName("message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DashScopeMessage? Message { get; set; }

    /// <summary>
    /// The reason the generation stopped
    /// </summary>
    [JsonPropertyName("finish_reason")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? FinishReason { get; set; }

    /// <summary>
    /// Index of this choice (for multi-choice responses)
    /// </summary>
    [JsonPropertyName("index")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Index { get; set; }
}

/// <summary>
/// DashScope usage DTO.
/// DashScope Token 使用量 DTO
/// </summary>
public class DashScopeUsage
{
    /// <summary>
    /// Input tokens
    /// </summary>
    [JsonPropertyName("input_tokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? InputTokens { get; set; }

    /// <summary>
    /// Output tokens
    /// </summary>
    [JsonPropertyName("output_tokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? OutputTokens { get; set; }

    /// <summary>
    /// Total tokens
    /// </summary>
    [JsonPropertyName("total_tokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? TotalTokens { get; set; }
}
